services:
  postgres:
    image: postgres:16-alpine
    container_name: falcao-erp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: falcao
      POSTGRES_PASSWORD: falcao
      POSTGRES_DB: falcao_erp
    ports:
      - "5432:5432"
    volumes:
      - falcao_erp_postgres_data:/var/lib/postgresql/data

volumes:
  falcao_erp_postgres_data:
